// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSghHwOUEPRhkOgSfp88Ey4pv6yVcWN4',
    appId: '1:123194228209:web:4363648157bdf9a2419850',
    messagingSenderId: '123194228209',
    projectId: 'fir-flutter-codelab-2c8bd',
    authDomain: 'fir-flutter-codelab-2c8bd.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2c8bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16UqMOmosMqV4joivQ2oHlxxERkiAQKU',
    appId: '1:123194228209:android:615610bc4450effb419850',
    messagingSenderId: '123194228209',
    projectId: 'fir-flutter-codelab-2c8bd',
    storageBucket: 'fir-flutter-codelab-2c8bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlY15QYuJACyOmu686U-42xDx6MYfgbA',
    appId: '1:123194228209:ios:ae70f9e014837f20419850',
    messagingSenderId: '123194228209',
    projectId: 'fir-flutter-codelab-2c8bd',
    storageBucket: 'fir-flutter-codelab-2c8bd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlY15QYuJACyOmu686U-42xDx6MYfgbA',
    appId: '1:123194228209:ios:daad1b68bf4d6d11419850',
    messagingSenderId: '123194228209',
    projectId: 'fir-flutter-codelab-2c8bd',
    storageBucket: 'fir-flutter-codelab-2c8bd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
